#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.5 on Tue Oct 28 14:08:30 2008 from /home/smagala/tasks/remap_fasta/gui/remap_fasta_gui.wxg

import wx

class GUIMainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: GUIMainFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.panel_1 = wx.Panel(self, -1)
        
        # Menu Bar
        self.main_frame_menubar = wx.MenuBar()
        self.SetMenuBar(self.main_frame_menubar)
        self.file_menu = wx.Menu()
        self.file_menu.AppendSeparator()
        self.exit_menu_option = wx.MenuItem(self.file_menu, wx.NewId(), "Exit", "Quit the Application", wx.ITEM_NORMAL)
        self.file_menu.AppendItem(self.exit_menu_option)
        self.main_frame_menubar.Append(self.file_menu, "File")
        # Menu Bar end
        self.main_frame_statusbar = self.CreateStatusBar(1, 0)
        self.label_1 = wx.StaticText(self.panel_1, -1, "FASTA File:", style=wx.ALIGN_RIGHT)
        self.fasta_box = wx.TextCtrl(self.panel_1, -1, "", style=wx.TE_READONLY)
        self.fasta_button = wx.Button(self.panel_1, -1, "Select")
        self.label_2 = wx.StaticText(self.panel_1, -1, "xls Map File:", style=wx.ALIGN_RIGHT)
        self.xls_box = wx.TextCtrl(self.panel_1, -1, "", style=wx.TE_READONLY)
        self.xls_button = wx.Button(self.panel_1, -1, "Select")
        self.run_button = wx.Button(self.panel_1, -1, "Re-map FASTA")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_MENU, self.OnExit, self.exit_menu_option)
        self.Bind(wx.EVT_BUTTON, self.on_get_fasta, self.fasta_button)
        self.Bind(wx.EVT_BUTTON, self.on_get_xls, self.xls_button)
        self.Bind(wx.EVT_BUTTON, self.on_remap, self.run_button)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: GUIMainFrame.__set_properties
        self.SetTitle("Re-Map FASTA Comments")
        self.main_frame_statusbar.SetStatusWidths([-1])
        # statusbar fields
        main_frame_statusbar_fields = [""]
        for i in range(len(main_frame_statusbar_fields)):
            self.main_frame_statusbar.SetStatusText(main_frame_statusbar_fields[i], i)
        self.fasta_box.SetMinSize((240, 27))
        self.xls_box.SetMinSize((240, 27))
        self.run_button.Enable(False)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: GUIMainFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_2 = wx.FlexGridSizer(2, 1, 5, 0)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.FlexGridSizer(3, 3, 5, 5)
        grid_sizer_1.Add(self.label_1, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.fasta_box, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.fasta_button, 0, 0, 0)
        grid_sizer_1.Add(self.label_2, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.xls_box, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.xls_button, 0, 0, 0)
        sizer_2.Add(grid_sizer_1, 1, wx.ALL, 5)
        grid_sizer_2.Add(sizer_2, 1, wx.EXPAND, 0)
        grid_sizer_2.Add(self.run_button, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        self.panel_1.SetSizer(grid_sizer_2)
        sizer_1.Add(self.panel_1, 1, wx.EXPAND, 5)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def OnExit(self, event): # wxGlade: GUIMainFrame.<event_handler>
        print "Event handler `OnExit' not implemented!"
        event.Skip()

    def on_get_fasta(self, event): # wxGlade: GUIMainFrame.<event_handler>
        print "Event handler `on_get_fasta' not implemented!"
        event.Skip()

    def on_get_xls(self, event): # wxGlade: GUIMainFrame.<event_handler>
        print "Event handler `on_get_xls' not implemented!"
        event.Skip()

    def on_remap(self, event): # wxGlade: GUIMainFrame.<event_handler>
        print "Event handler `on_remap' not implemented!"
        event.Skip()

# end of class GUIMainFrame


class GUIApp(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        main_frame = GUIMainFrame(None, -1, "")
        self.SetTopWindow(main_frame)
        main_frame.Show()
        return 1

# end of class GUIApp

if __name__ == "__main__":
    app = GUIApp(0)
    app.MainLoop()
